GET http://localhost:8080/contacts

###

GET http://localhost:8080/contacts/ID_HERE

###

POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@gmail.com",
  "favoriteColor": "blue",
  "birthday": "2000-01-01"
}

###

PUT http://localhost:8080/contacts/ID_HERE
Content-Type: application/json

{
  "firstName": "John Updated"
}

###

DELETE http://localhost:8080/contacts/ID_HERE